version: "3.7"

services:

  main:
    container_name: nexus-main
    image: mcr.microsoft.com/dotnet/sdk:8.0
    volumes:
      - /var/lib/nexus/docker/nexus-main/.ssh:/root/.ssh
    entrypoint: bash -c "cd; curl -s -O 'https://raw.githubusercontent.com/nexus-main/nexus-sources-remote/master/setup/docker/setup-main.sh'; source 'setup-main.sh'"
    restart: always

  satellite-python:
    container_name: nexus-python
    image: python:3.9.0
    volumes:
      - /var/lib/nexus/docker/nexus-python/.ssh:/root/.ssh
    entrypoint: bash -c "satellite_id=python;cd; curl -s -O 'https://raw.githubusercontent.com/nexus-main/nexus-sources-remote/master/setup/docker/setup-satellite.sh'; source 'setup-satellite.sh'"
    restart: always

  satellite-nexus:
    container_name: nexus-dotnet
    image: mcr.microsoft.com/dotnet/sdk:8.0
    volumes:
      - /var/lib/nexus/docker/nexus-dotnet/.ssh:/root/.ssh
    entrypoint: bash -c "satellite_id=dotnet;cd; curl -s -O 'https://raw.githubusercontent.com/nexus-main/nexus-sources-remote/master/setup/docker/setup-satellite.sh'; source 'setup-satellite.sh'"
    restart: always
